# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: "0.2.0"
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Firefox
      directives:
        description: Install Firefox
        allowPrerelease: true
      settings:
        id: Mozilla.Firefox
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Elgato_WaveLink
      directives:
        description: Install Elgato WaveLink
        allowPrerelease: true
      settings:
        id: Elgato.WaveLink
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Elgato_StreamDeck
      directives:
        description: Install Elgato StreamDeck
        allowPrerelease: true
      settings:
        id: Elgato.StreamDeck
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Elgato_Control_Center
      directives:
        description: Install Elgato Control Center
        allowPrerelease: true
      settings:
        id: Elgato.ControlCenter
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WhatsApp
      directives:
        description: Install WhatsApp
        allowPrerelease: true
      settings:
        id: WhatsApp.WhatsApp
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Spotify
      directives:
        description: Install Spotify
        allowPrerelease: true
      settings:
        id: Spotify.Spotify
        source: winget
